"use client";

import { useMemo, useState, useTransition, type FormEvent } from "react";
import { useRouter } from "next/navigation";

import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Field, Label } from "@/components/ui/label";
import { Select, type SelectOption } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/toast";
import { useDict, useLocale } from "@/lib/i18n/client";
import { fmt } from "@/lib/i18n/format";

import { postLedgerEntry } from "./actions";

/** A payee the finance user may post against, keyed by the polymorphic pair. */
export type PayeePickOption = {
  payee_type: "model" | "operator";
  payee_id: string;
  label: string;
};

type EntryType = "adjustment" | "deduction";

type FormState = {
  payee: string; // `${payee_type}:${payee_id}`
  entry_type: EntryType;
  amount: string;
  currency: string;
  description: string;
};

const INITIAL: FormState = {
  payee: "",
  entry_type: "adjustment",
  amount: "",
  currency: "USD",
  description: "",
};

function num(value: string): number {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
}

/**
 * Post a manual ledger movement — an `adjustment` (± correction) or a `deduction`
 * (amount withheld, always stored negative). The ledger is append-only (docs/09
 * §5.2): there is no edit or delete; a mistake is corrected by a reversing entry.
 * `earning_share` and `payout_settlement` are deliberately NOT offered here — the
 * first is generated by "Close period", the second is trigger-only.
 */
export function PostEntryForm({ payees }: { payees: PayeePickOption[] }) {
  const router = useRouter();
  const d = useDict();
  const fm = fmt(useLocale());
  const { success, error } = useToast();
  const [open, setOpen] = useState(false);
  const [isRunning, startTransition] = useTransition();
  const [form, setForm] = useState<FormState>(INITIAL);

  const payeeOptions: SelectOption[] = useMemo(
    () => payees.map((p) => ({ value: `${p.payee_type}:${p.payee_id}`, label: p.label })),
    [payees],
  );

  const entryOptions: SelectOption[] = [
    { value: "adjustment", label: d.money.ledger.postAdjustmentOption },
    { value: "deduction", label: d.money.ledger.postDeductionOption },
  ];

  const magnitude = Math.abs(num(form.amount));
  const previewSign = form.entry_type === "deduction" ? -1 : num(form.amount) < 0 ? -1 : 1;
  const preview = magnitude === 0 ? 0 : previewSign * magnitude;

  function openDialog() {
    setForm(INITIAL);
    setOpen(true);
  }

  function close() {
    if (isRunning) return;
    setOpen(false);
  }

  function set<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const [payee_type, payee_id] = form.payee.split(":");

    startTransition(async () => {
      const result = await postLedgerEntry({
        payee_type: payee_type as "model" | "operator",
        payee_id: payee_id ?? "",
        entry_type: form.entry_type,
        amount: form.amount,
        currency: form.currency,
        description: form.description,
      });

      if (result.ok) {
        success(d.money.ledger.postToastOk, result.message);
        setOpen(false);
        router.refresh();
      } else {
        error(d.money.ledger.postToastErr, result.error);
      }
    });
  }

  const noPayees = payees.length === 0;

  return (
    <>
      <Button onClick={openDialog}>{d.money.ledger.postCta}</Button>

      <Dialog
        open={open}
        onClose={close}
        dismissible={!isRunning}
        title={d.money.ledger.postTitle}
        description={d.money.ledger.postDesc}
        size="lg"
        footer={
          <>
            <Button variant="ghost" onClick={close} disabled={isRunning}>
              {d.common.cancel}
            </Button>
            <Button type="submit" form="ledger-entry-form" loading={isRunning} disabled={noPayees}>
              {d.money.ledger.postSubmit}
            </Button>
          </>
        }
      >
        {noPayees ? (
          <p className="text-sm text-muted">{d.money.ledger.postNoPayees}</p>
        ) : (
          <form id="ledger-entry-form" onSubmit={submit} className="flex flex-col gap-4">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Field help={d.money.ledger.postPayeeHelp}>
                <Label htmlFor="ledger-payee" required>
                  {d.money.ledger.payee}
                </Label>
                <Select
                  id="ledger-payee"
                  required
                  placeholder={d.money.ledger.postSelectPayee}
                  options={payeeOptions}
                  value={form.payee}
                  onChange={(e) => set("payee", e.target.value)}
                />
              </Field>

              <Field
                help={
                  form.entry_type === "deduction"
                    ? d.money.ledger.postDeductionHelp
                    : d.money.ledger.postAdjustmentHelp
                }
              >
                <Label htmlFor="ledger-type" required>
                  {d.money.ledger.postEntryTypeLabel}
                </Label>
                <Select
                  id="ledger-type"
                  required
                  options={entryOptions}
                  value={form.entry_type}
                  onChange={(e) => set("entry_type", e.target.value as EntryType)}
                />
              </Field>
            </div>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Field
                help={
                  form.entry_type === "deduction"
                    ? d.money.ledger.postAmountHelpDeduction
                    : d.money.ledger.postAmountHelpAdjustment
                }
              >
                <Label htmlFor="ledger-amount" required hint={d.money.ledger.postAmountHint}>
                  {d.money.ledger.postAmount}
                </Label>
                <Input
                  id="ledger-amount"
                  type="number"
                  inputMode="decimal"
                  step="0.01"
                  required
                  value={form.amount}
                  onChange={(e) => set("amount", e.target.value)}
                />
              </Field>

              <Field help={d.money.ledger.postCurrencyHelp}>
                <Label htmlFor="ledger-currency" required>
                  {d.money.ledger.postCurrency}
                </Label>
                <Input
                  id="ledger-currency"
                  autoComplete="off"
                  maxLength={3}
                  required
                  value={form.currency}
                  onChange={(e) => set("currency", e.target.value.toUpperCase())}
                  placeholder="USD"
                  className="uppercase"
                />
              </Field>
            </div>

            <Field help={d.money.ledger.postDescriptionHelp}>
              <Label htmlFor="ledger-note">{d.money.ledger.postDescription}</Label>
              <Textarea
                id="ledger-note"
                rows={2}
                value={form.description}
                onChange={(e) => set("description", e.target.value)}
                placeholder={d.money.ledger.postDescriptionPlaceholder}
              />
            </Field>

            <p
              className={
                preview < 0 ? "text-xs text-danger" : "text-xs text-muted"
              }
            >
              {d.money.ledger.postsAs(fm.money(preview, form.currency || "USD", { signed: true }))}
            </p>
          </form>
        )}
      </Dialog>
    </>
  );
}
