"use client";

import { useMemo, useState, useTransition, type FormEvent } from "react";
import { useRouter } from "next/navigation";

import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Field, Label } from "@/components/ui/label";
import { Select, type SelectOption } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/toast";
import { money } from "@/lib/format";

import { postLedgerEntry } from "./actions";

/** A payee the finance user may post against, keyed by the polymorphic pair. */
export type PayeePickOption = {
  payee_type: "model" | "operator";
  payee_id: string;
  label: string;
};

type EntryType = "adjustment" | "deduction";

type FormState = {
  payee: string; // `${payee_type}:${payee_id}`
  entry_type: EntryType;
  amount: string;
  currency: string;
  description: string;
};

const INITIAL: FormState = {
  payee: "",
  entry_type: "adjustment",
  amount: "",
  currency: "USD",
  description: "",
};

function num(value: string): number {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
}

/**
 * Post a manual ledger movement — an `adjustment` (± correction) or a `deduction`
 * (amount withheld, always stored negative). The ledger is append-only (docs/09
 * §5.2): there is no edit or delete; a mistake is corrected by a reversing entry.
 * `earning_share` and `payout_settlement` are deliberately NOT offered here — the
 * first is generated by "Close period", the second is trigger-only.
 */
export function PostEntryForm({ payees }: { payees: PayeePickOption[] }) {
  const router = useRouter();
  const { success, error } = useToast();
  const [open, setOpen] = useState(false);
  const [isRunning, startTransition] = useTransition();
  const [form, setForm] = useState<FormState>(INITIAL);

  const payeeOptions: SelectOption[] = useMemo(
    () => payees.map((p) => ({ value: `${p.payee_type}:${p.payee_id}`, label: p.label })),
    [payees],
  );

  const entryOptions: SelectOption[] = [
    { value: "adjustment", label: "Adjustment (±)" },
    { value: "deduction", label: "Deduction (−)" },
  ];

  const magnitude = Math.abs(num(form.amount));
  const previewSign = form.entry_type === "deduction" ? -1 : num(form.amount) < 0 ? -1 : 1;
  const preview = magnitude === 0 ? 0 : previewSign * magnitude;

  function openDialog() {
    setForm(INITIAL);
    setOpen(true);
  }

  function close() {
    if (isRunning) return;
    setOpen(false);
  }

  function set<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const [payee_type, payee_id] = form.payee.split(":");

    startTransition(async () => {
      const result = await postLedgerEntry({
        payee_type: payee_type as "model" | "operator",
        payee_id: payee_id ?? "",
        entry_type: form.entry_type,
        amount: form.amount,
        currency: form.currency,
        description: form.description,
      });

      if (result.ok) {
        success("Ledger entry posted", result.message);
        setOpen(false);
        router.refresh();
      } else {
        error("Could not post entry", result.error);
      }
    });
  }

  const noPayees = payees.length === 0;

  return (
    <>
      <Button onClick={openDialog}>Post adjustment</Button>

      <Dialog
        open={open}
        onClose={close}
        dismissible={!isRunning}
        title="Post a ledger entry"
        description="Manual corrections only. The ledger is append-only — fix a wrong posting with a reversing adjustment, never an edit (docs/09 §5.2)."
        size="lg"
        footer={
          <>
            <Button variant="ghost" onClick={close} disabled={isRunning}>
              Cancel
            </Button>
            <Button type="submit" form="ledger-entry-form" loading={isRunning} disabled={noPayees}>
              Post entry
            </Button>
          </>
        }
      >
        {noPayees ? (
          <p className="text-sm text-muted">
            No payees are available. Add a model or operator first — every ledger entry targets
            exactly one payee.
          </p>
        ) : (
          <form id="ledger-entry-form" onSubmit={submit} className="flex flex-col gap-4">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Field help="Money is owed to a model or operator — never the studio (docs/09 §1).">
                <Label htmlFor="ledger-payee" required>
                  Payee
                </Label>
                <Select
                  id="ledger-payee"
                  required
                  placeholder="Select a payee…"
                  options={payeeOptions}
                  value={form.payee}
                  onChange={(e) => set("payee", e.target.value)}
                />
              </Field>

              <Field
                help={
                  form.entry_type === "deduction"
                    ? "Withheld from the payee — stored as a negative amount."
                    : "A correction: positive credits the payee, negative reverses a prior posting."
                }
              >
                <Label htmlFor="ledger-type" required>
                  Entry type
                </Label>
                <Select
                  id="ledger-type"
                  required
                  options={entryOptions}
                  value={form.entry_type}
                  onChange={(e) => set("entry_type", e.target.value as EntryType)}
                />
              </Field>
            </div>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Field
                help={
                  form.entry_type === "deduction"
                    ? "Enter the amount to withhold; the sign is applied for you."
                    : "Use a minus sign to reverse an earlier credit."
                }
              >
                <Label htmlFor="ledger-amount" required hint="≠ 0">
                  Amount
                </Label>
                <Input
                  id="ledger-amount"
                  type="number"
                  inputMode="decimal"
                  step="0.01"
                  required
                  value={form.amount}
                  onChange={(e) => set("amount", e.target.value)}
                />
              </Field>

              <Field help="3-letter code, e.g. USD.">
                <Label htmlFor="ledger-currency" required>
                  Currency
                </Label>
                <Input
                  id="ledger-currency"
                  autoComplete="off"
                  maxLength={3}
                  required
                  value={form.currency}
                  onChange={(e) => set("currency", e.target.value.toUpperCase())}
                  placeholder="USD"
                  className="uppercase"
                />
              </Field>
            </div>

            <Field help="Optional. Recorded on the entry for provenance.">
              <Label htmlFor="ledger-note">Description</Label>
              <Textarea
                id="ledger-note"
                rows={2}
                value={form.description}
                onChange={(e) => set("description", e.target.value)}
                placeholder="e.g. Reversal of duplicated March share"
              />
            </Field>

            <p className="text-xs text-muted">
              Posts as:{" "}
              <span
                className={
                  preview < 0 ? "font-medium text-danger" : "font-medium text-foreground"
                }
              >
                {money(preview, form.currency || "USD", { signed: true })}
              </span>
            </p>
          </form>
        )}
      </Dialog>
    </>
  );
}
